### ISSUE TITLE
head

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#11]
Before progressing to other data types than organizations it might be worth deciding on an approach for `<head>` data. I've only used react-helmet, but it might be worth seeing if simpler/smaller alternatives like react-document-title solves our modest needs. Other suggestions are much welcomed

**Comment by luckyluck** [comment]
I pushed changes into the dataset branch. Could you please look at it?
I decided to go with react-document-title because of simplicity. There is a probable issue - Dan Abramov somehow forgot about this library and does not manage pull requests for 2 years. If we need something with a TypeScript support or with a wider functionality, we'll have to look at other solutions like Helmet or [react-head](https://github.com/tizmagik/react-head).
