### ISSUE TITLE
cannot create organization language

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#227]
https://gbif-registry-demo.netlify.com/organization/create
click language. enter letter. site crashes

**Comment by MortenHofft** [comment]
I see this has been closed as "impossible to solve". I do not agree. It should just filter the translated values. That is what we do in our other apps. E.g. country filter on this page https://www.gbif.org/occurrence/search?q=

**Comment by luckyluck** [comment]
@MortenHofft, Initially I thought that it wasn't a good idea to filter languages using translation because of performance (that was in my mind). And I removed the filter on Dataset from and forgot to do the same for Organization. Now I implemented a filter which translates then compares the value with the user's input. If we do not have a translation for the language code (new language), such language will not appear in any filter results. As I checked the filter locally and on Netlify, I am going to close the issue.
