### ISSUE TITLE
Pending endorsements missing from menu

### ISSUE THREAD

**Issue by jlegind** [gbif/registry-console#242]
The "Pending endorsements" section disappeared and I would like to have it back because it helps us monitor these cases.

The landing page 'pending' link only shows those publishers that are pending endorsement from the GBIF Secretariat node.

**Comment by MortenHofft** [comment]
The list off all pending wasn't carried to the new layout with table filters I see. It should be added as one of the filters.
<img width="534" alt="screen shot 2019-03-01 at 12 26 55" src="https://user-images.githubusercontent.com/6759267/53609981-694ec980-3c1d-11e9-9f47-457e184a449f.png">

and then add the link on the homepage as well

**Comment by luckyluck** [comment]
@MortenHofft, would you mind to clarify this issue? I checked again all the changes that I did refactoring layout to use filters instead of multi pages and found that I moved all pages. The only place where we had and still have pending endorsements is Node details page like [this](https://master--gbif-registry-demo.netlify.com/node/be9956ea-f43e-4746-b333-64e04ef5100e/pending).

**Comment by MortenHofft** [comment]
ahh. May bad - i looked at institutions, not organizations (i have a tendency to mix those). @jlegind it is there as a filter on the table.
