### ISSUE TITLE
missing translation keys

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#278]
![Screenshot 2019-04-29 at 10 19 20](https://user-images.githubusercontent.com/6759267/56883879-477c9200-6a68-11e9-8c27-f5b217669810.png)

**Comment by MortenHofft** [comment]
I see that the issue is that the translation request isn't versioned. So the users end up with a stale version and need to clear cache locally. that won't work

**Comment by MortenHofft** [comment]
Looking (quickly) at the requests, the translation file is the only request that I see that is missing cache busting.

**Comment by luckyluck** [comment]
@MortenHofft, I would recommend solving this issue in this way:

1. using versioning for the project https://docs.npmjs.com/cli/version.html
2. adding version as a global variable to .env.local like here https://stackoverflow.com/a/50822003/2185053
3. putting ${process.env.REACT_APP_VERSION} instead of ${Date.now()}

In that case, we should run the command `npm version patch` (or similar for bigger changes) every time we fix a bug. And after that, a new version will be added as a part of the link.
Also, I will update README by adding new rules if you approve this solution.
