### ISSUE TITLE
Running ingestions page frequently brings up an error

### ISSUE THREAD

**Issue by rukayaj** [gbif/registry-console#289]
Hi :) When i access the running ingestions page, or often if i turn on the live tickbox, i'm getting this error "An error occurred
An error happened while trying to process your request. Please report the error at https://github.com/gbif/portal-feedback/issues/new" . 

Nothing in the javascript console apart from a message about cross origin read blocking which I think appears even without the error. 

I'm using Chrome. I would say it's happening 3 times out of 5 when I try access the page, but it's not consistent.

**Comment by MortenHofft** [comment]
Thanks
When you say ingestion page which do you mean? Could you provide the link please? 
`Running ingestions` or the `overingested datasets` or a specific datasets ingestions?

**Comment by rukayaj** [comment]
Yeah, it's running ingestions https://registry.gbif.org/monitoring/ingestion. I thought I had it in my title but I see it could be read as accessing the ingestions page! It seems to have stabilised a bit over the last hour or so, so could be there was just something funny happening with the API?

**Comment by MortenHofft** [comment]
That is annoying. The API for this is very slow, but I haven't experienced it failing. I wonder if it is related to https://github.com/gbif/registry-console/issues/272

**Comment by MortenHofft** [comment]
Sounds like an API thing, but I cannot reproduce it just now. @ManonGros let me know if you also notice this behaviour please.

**Comment by ManonGros** [comment]
I haven't experience this but so far I haven't used this ingestion page much.

**Comment by MattBlissett** [comment]
> The API for this is very slow

Only if we have a very large queue (many hundreds), which is rare.  https://api.gbif.org/v1/dataset/process/running returns in about 15ms for me.

It looks to me like the old interface does one request when "Live View" is selected (i.e. https://api.gbif.org/v1/dataset/process/running ), but the new one does that, plus re-requests the dataset information and current occurrence count.

The dataset information can change, if there is a change due to ingestion of updated metadata, but I think the only thing that's shown is the title. It's not really worth checking if the title has changed every 2 seconds.

The occurrence counts would change, although the responses are cached for 10 minutes. It could be re-checked after 10 minutes, or not at all.

Also, the new one does an OPTIONS request for all of these, but the old one doesn't do any OPTIONS requests.

**Comment by MortenHofft** [comment]
Thanks Matt and yes I too have noticed that the new implementation is more liberal with its use of requests - that is largely why I created https://github.com/gbif/registry-console/issues/272 . Using the cahced API for datasets would help (with the risk of getting a stale title). If it becomes an issue I will do a local cache like the old version had.

**Comment by MortenHofft** [comment]
I'm guessing this was also related to https://github.com/gbif/registry-console/issues/347
The issue being that the occurrence API will occasionally fail when an auth header is present. Auth is not used for the occ api and the header have been removed.

Let me know if this is still an issue.
