### ISSUE TITLE
New filters for pipeline history overview

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry-console#328]
The pipeline history table would benefit from filters to 

1. Only show datasets for a publisher, country or installation (e.g. show me only MgNify datastes)
2. Sort by date (either be a start or end date) to enable easy way to diagnose things such as datasets for a publisher that haven't been crawled today
3. Show crawls that have a failed step to diagnose things that broke recently

**Comment by MortenHofft** [comment]
The interface and API's have changed quite a lot since this issue was created. 

It would be this page https://registry.gbif.org/monitoring/ingestion-history
using [this api](https://api.gbif.org/v1/pipelines/history). I do not believe the API supports such functionalities currently.

it is possible to see the history for an individual dataset using https://registry.gbif.org/dataset/0362f4dc-1cdd-4e90-a3ed-ca05bbe1044f/ingestion-history

@timrobertson100 if this is still relevant, then I will move the issue to the registry as the API needs new features before this can progress.

**Comment by timrobertson100** [comment]
Closing as these don't seem like things we struggle with in production.
