### ISSUE TITLE
Organisation endorsement improvements

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/registry-console#345]
- [x] Replace the 'endorsement approved' checkbox with just a status (text).

- [x] Remove the 'endorsement approved' checkbox from the organization creation form

- [x] Add the organization endorsement status and endorsed date to the view page.
Possible statuses: ENDORSED, REJECTED, WAITING_FOR_ENDORSEMENT, ON_HOLD

- [x] Add button to approve or revoke endorsement of the organization (depends on the 'endorsementApproved' field of the organization)
The button should only be visible to the admin or user with editor rights. Check:
GET / organization / {key} / endorsement / user / {user}
2xx - display button
4xx - hide button
Endpoints for endorsement:
PUT / organization / {key} / endorsement
DELETE / organization / {key} / endorsement

**Comment by ahahn-gbif** [comment]
reopening, sorry - a couple of additional things, please:

- add the new "endorsed" date field to the UI (read-only)
- make the ON_HOLD status available for selection (currently not accessible at all)
- in addition to the current transitions
-- waiting -> endorsed ( *** )
-- endorsed -> rejected
-- rejected -> endorsed
also allow for 
-- waiting -> rejected ( * )
-- waiting -> on hold ( * )
-- on hold -> endorsed ( * )
-- on hold -> rejected ( * )
( *** covers the vast majority of cases, * also occurs occasionally, the others as good as never)

in particular: we do not want to go through a sequence of _waiting > endorsed > rejected_ in order to reach rejected - it may trigger some unwanted time stamps / mail shoots

**Comment by thomasstjerne** [comment]
I would simply implement this as a dropdown where the state is selected. Then transitions between any two states are possible.
The question is whether the picklist should be shown to only registry admins or also the node manager (that has access to endorsement as well)?
Or should we stick to the simple button for the node manager?

**Comment by ahahn-gbif** [comment]
+1 for dropdown

Editing: Only registry admins
Read access (everybody else) should only show the current state, not the possible transitions

The majority of regular operations (endorsements) happens through an email workflow via the registry backend - Node managers do not use the editing interface for this purpose. Only in cases where email communication with Node Managers urges "holding" or "rejecting" an endorsement, the UI access is needed, and the update will be handled by registry admins, not by node managers.

**Comment by thomasstjerne** [comment]
> new "endorsed" date field to the UI (read-only)

I dont think this field is in the API yet

**Comment by mike-podolskiy90** [comment]
@thomasstjerne no, it was added recently, e.g. http://api.gbif-dev.org/v1/organization/42142208-1e2d-460c-9816-09c803ea2b1b
