### ISSUE TITLE
Update GRSciColl UI to reflect the way we now use machineTags and identifiers

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#379]
The machineTags will now be used for IH synch (https://github.com/gbif/registry/issues/342) instead of identifiers.

- [x] This means that the machineTag (and not the identifier) should be used to show the label "Master record: Index Herbariorum".

- [ ] Something else to modify and this is a bit more complicated. Editors should still be given the possibility to "disconnect" an institution from IH. In practise, that means deleting the IH machineTag but we don't want editors to do it directly.
Ideally, what we need is some way for the UI to offer the possibility to disconnect from IH. I am not sure what would be the best way to implement that. We can discuss several possible solutions.

**Comment by MortenHofft** [comment]
It would be nice with some more context for this.

Is IH still in the identifiers? So that the IH identifier is kept even if the owner decides to break the syncing?
Is the IH link double encoded in both machineTag and identifier? What happens if they differ?

What is the namespace of these? What is the general format? Are there any examples? Is the machine tag used to indicate which identifier *type* to use or does it *hold* the identifier?

**Comment by MortenHofft** [comment]
I found an example
https://api.gbif-dev.org/v1/grscicoll/institution/c4b0b9e6-41db-41bb-88de-09341e480765/machineTag

**Comment by MortenHofft** [comment]
UPDATE:

I just had a call with @ManonGros 
the intention is to leave the identifiers as is and also encode the identifier again in the machine tag. 
So the 2 can in theory be different. We will ignore that for now.

https://registry.gbif-dev.org/institution/c4b0b9e6-41db-41bb-88de-09341e480765/machineTag

**Comment by MortenHofft** [comment]
I'm closing this issue in favour of 
https://github.com/gbif/registry-console/issues/430
https://github.com/gbif/registry-console/issues/428
https://github.com/gbif/registry-console/issues/429
