### ISSUE TITLE
not all registry terms in crowding translation project

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#400]
I am not sure if this is the best place to log that. But I am trying to put in crowding the translation for the GRSciColl part of the registry and it seems like some terms are missing.
For example:
* https://crowdin.com/translate/gbif-registry/all/en-es?filter=basic&value=0#q=Preservation%20type
* https://crowdin.com/translate/gbif-registry/all/en-es?filter=basic&value=0#q=Incorporated%20collections

Am I missing something?

**Comment by MortenHofft** [comment]
No you are not. Not all terms are in the project. Since there has been no interest in translating it until now we haven't made much effort to ensure that everything is in Crowdin. 

I understand that your primary interest is GrSciColl entities, I will go through those and make sure all terms are included in the translation file.

**Comment by MortenHofft** [comment]
I've added what I believe is the missing terms for grscicoll. If I have missed any (it isn't unlikely), please create an issue and I will add them

**Comment by ManonGros** [comment]
Thanks @Morten, this is great!
