### ISSUE TITLE
Cannot pick my institution when editing a dataset's publishing organization

### ISSUE THREAD

**Issue by FedorSteeman** [gbif/registry-console#452]
I have been trying to change the publishing organization of [a particular dataset](https://registry.gbif.org/dataset/e0459621-92c2-40ac-9934-72b3b1384dc3) into my own, which I know has been [registered in GrSciColl](https://registry.gbif.org/institution/68fcaba0-61fe-4e78-a460-4f37654d025d). Whenever I type in the name, the pick list remains empty and says "Not found", barring me from picking "Natural History Museum of Denmark". 

![image](https://user-images.githubusercontent.com/10909008/151961879-79a89cbc-ead1-4234-92b3-643af66b3d2c.png)

I have tried in Chrome, Firefox and Edge with the exact same results.

**Comment by ManonGros** [comment]
Note that it works for me, not sure why this isn't the case for Fedor (he has the permissions to make the change):
<img width="876" alt="Screenshot 2022-02-01 at 13 21 31" src="https://user-images.githubusercontent.com/7677271/151967519-e1b5b475-7754-41f9-9a2e-e5e5c75c7fa1.png">
 
@FedorSteeman note that the organization has to be in the "organization" part of the registry (GRSciColl is independent). This is the case here though: https://registry.gbif.org/organization/2e7df380-8356-4533-bcb3-5459e23c794e

**Comment by MortenHofft** [comment]
The issue with it being an institution aside, then the suggest should work for that name, it just isn't the entity you link to.

I can reproduce it if I add spacing in the end. It looks like you have spacing in the beginning. The UI should trim that and the backend should probably ignore it as well.
Perhaps that is the reason? I also noticed that the suggest endpoint took quite long to respond the first time around, which is odd, it is normally fast.

Can you still reproduce this @FedorSteeman ? Thank you for your help.

**Comment by FedorSteeman** [comment]
@MortenHofft The issue is still exactly the same as before. I'm not writing any spacing in the beginning. I start with the letter 'N' and proceed from there.

**Comment by FedorSteeman** [comment]
I discovered that it *does* work in UAT. Just not in PROD. 

![image](https://user-images.githubusercontent.com/10909008/152111360-a3844b26-6ceb-4776-a32b-89a9e1fb7cc1.png)

**Comment by MortenHofft** [comment]
UAT was running a slightly newer version that wasn't deployed to prod, but I do not see what difference it would make in this context. 
You do however have different rights in UAT and production. And if I create a user with the same rights as you, then I cannot see the suggestion either

**Comment by ManonGros** [comment]
I made a user with the same permissions as Fedor and names don't appear as I write in the field but if I paste the UUID of a different Danish organization, it works (I can change the organization). So the issue seems to be with the organisation suggestion function.
<img width="649" alt="Screenshot 2022-02-02 at 11 39 27" src="https://user-images.githubusercontent.com/7677271/152138406-9fb8574f-ec76-4ce9-8ba9-b1579ed389ba.png">

**Comment by MortenHofft** [comment]
yes, the problem is that the endorsing node key isn't included in the suggest endpoint. but if you paste a uuid, then it fetches the actual entity which includes the value. So I either have to use the slow search or we change suggest to include endorsingNodeKey.

The UI need the endorsingNodeKey as it tries to deduce if the user has editing rights. But with our new model of managing access rights, the UI should perhaps just allow the user to select any value and then leave it to the backend to validate it. Or for the backend to add a new endpoint that only suggests valid values.

Does having a country scope give access to any organisations within the country?

**Comment by ManonGros** [comment]
I see, it would make sense for the future to handle it in the backend (although I see that you already fixed the issue for now).

Having a Node scope gives you access to any organization endorsed by the Node. The "country" scope applies only to GRSciColl (you can access institution and collections in the country).

**Comment by MortenHofft** [comment]
I've changed it to use the search endpoint instead of the suggest, but that means that it will be much slower. But at least it will work. If we want it fast and functional then we should extend the backend to include endorsingNodeKey in the suggest endpoint
