### ISSUE TITLE
Translation - separate GRSciColl from other registry terms

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry-console#500]
Not sure which repo would be right for this here I go:
Is there any way to separated the translation of GRSciColl terms from the other registry terms in Crowdin?
Right now, everything is mixed in one folder. There is a CESP project aiming to translate the GRSciColl editing interface but they don't have the resources to translate everything. Is there a way we could make their job easier?

**Comment by MortenHofft** [comment]
I do not think so. Perhaps there is a way to group terms in Crowdin @dnoesgaard?

**Comment by dnoesgaard** [comment]
I can't really think of a way, except if the "GRSciColl terms" were already grouped, e.g. by a common key in the translations.

But searching for few keywords in the context might help?

Like https://crowdin.com/translate/gbif-registry/440/en-fr?filter=basic&value=0#q=collection ?

**Comment by dnoesgaard** [comment]
"institution" is probably another good one

**Comment by dnoesgaard** [comment]
I think it would require renaming all the relevant translation strings and changing the code wherever these are used.

For example these strings are easy because they already contain "grSciColl" in the key:
"menu.grSciCollPerson": "GRSciColl staff",
"menu.grSciCollPerson.search": "GRSciColl staff search",
"menu.grSciCollPerson.deleted": "GRSciColl staff deleted"

But you could in theory identify all the relevant translation keys and give them a prefix

grSciColl.xyz.abc
etc.

Searching for the "grSciColl" in the context would then bring them up.

**Comment by ManonGros** [comment]
Thanks for the explanations! Since we already use `collection` and `institution` for the terms related to GRSciColl, it would probably be enough to just use those for searches. I will relay the information.
Thank you both!
