### ISSUE TITLE
country select search limited to codes

### ISSUE THREAD

**Issue by mnhn-paul** [gbif/registry-console#569]
I noticed that the select country field is limited to searching for country codes, eg. "LU" gives "Luxembourg" but "LUX" does not give any results.
This is a bit counter-intuitive, not sure if this is suppose to the desired behavior. 

![image](https://github.com/gbif/registry-console/assets/26623703/b5192254-e2da-40ac-ab51-9574c31e5a13)

**Comment by MortenHofft** [comment]
It is a known issue, but there is a tendency to accept bad tooling internally - things that we would never put to production for a generalist user site. And since the registry started as an internal tool many features are crude and require knowing the workarounds.

In this case the technical reason is that translations aren't searched, only the "real" value - namely the country code. Obviously this is't ideal.

**Comment by MortenHofft** [comment]
Fixed and deployed to production

**Comment by mnhn-paul** [comment]
thanks for the explications and fixing this
