### ISSUE TITLE
Right to left languages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#88]
Our main website are intended to support rtl language by mid 2019. That means that the registry should as well. 

For some parts Antd controls it in a way that makes it difficult to change. Those parts could probably largely be overwritten by css, but doing so in antd is probably better. 

There is a discussion about rtl in antd
https://github.com/ant-design/ant-design/issues/4051

**Comment by MortenHofft** [comment]
This by the way is largely the reason I introduced a theme provider. https://github.com/gbif/registry-console/blob/master/src/components/App.js#L65

**Comment by luckyluck** [comment]
@MortenHofft, adapting console to work for rtl languages, I improved styles not only for custom components but for Ant Design library too.
As I understood, there are no problems with components which use flexbox or float styles, 
because such CSS styles support rtl out of the box.

Most problems I found in components which use positioning, absolute and relative.
Some of the issues I fixed rewriting default styles using flexbox - in those cases, everything works for both directions.
But some issues I fixed using specially added class 'rtl-direction' to the body element.
That means that in those cases we have different styles for different directions.
Perhaps, it's possible to get rid of such changes later using only flexbox.

So far, I spent 6 hours 45 minutes this time and approximately the same amount of hours previous time I worked with the issue.
IMHO, I would spend much more if I tried to dig into the source code and create a couple of pull requests to the official repository.

I added all styles for the Ant Design library to the bottom of App.css with comments.
Changes available here https://rtl--gbif-registry-demo.netlify.com/ and you should choose the Hebrew language to switch console to rtl.

Also, below you can see a couple of screenshots.

**Comment by luckyluck** [comment]
![0ab68b3bbe](https://user-images.githubusercontent.com/2361566/52613461-333ce600-2eb8-11e9-908c-ea3ede6ef13c.png)
![689ef526dc](https://user-images.githubusercontent.com/2361566/52613462-333ce600-2eb8-11e9-989c-d6e1fb72a7ae.png)
![345786a2d3](https://user-images.githubusercontent.com/2361566/52613463-33d57c80-2eb8-11e9-9ffc-d45254b26152.png)
![a7062541fe](https://user-images.githubusercontent.com/2361566/52613464-33d57c80-2eb8-11e9-9a3d-855dd69fb2e1.png)
![bd5edf6774](https://user-images.githubusercontent.com/2361566/52613465-33d57c80-2eb8-11e9-8baf-86290949cc93.png)
![f7edeba687](https://user-images.githubusercontent.com/2361566/52613466-33d57c80-2eb8-11e9-8e6c-4f53bebefdae.png)

**Comment by MortenHofft** [comment]
That is great and good news! Thank you. Sounds like we should continue. It looks good from your screenshots. Could you please review mobile? I see the menu doesn’t work there.

**Comment by MohammadMobasher** [comment]
[luckyluck](/luckyluck) how to i can get this css from you?!

**Comment by luckyluck** [comment]
> [luckyluck](/luckyluck) how to i can get this css from you?!
> i mean trl css

You can find changes for rtl that I did in CSS right [here](https://github.com/gbif/registry-console/blob/rtl/src/components/App.css#L150). But these changes were done mainly for Ant Design library. Some changes were added directly in components using [react-jss](https://github.com/cssinjs/react-jss). You can check commits that attached to this issue if you want more details.
By the way, in some places it was enough just to add flexbox styles.

**Comment by MohammadMobasher** [comment]
can you get me some example?!

**Comment by luckyluck** [comment]
> can you get me some example?!

As an example, you can check [this](https://github.com/gbif/registry-console/commit/1af1e1a7a0e85b6873d2b936094a66fc81677e04) commit or [this](https://github.com/gbif/registry-console/commit/c39661ea403a702958d730b3fe84575f2425b594) one.
